/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GC */

#ifndef _Included_GC
#define _Included_GC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GC
 * Method:    maxObjectInspectionAge
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_GC_maxObjectInspectionAge
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
